# Mirror of GitHub Actions workflow (for rubric folder structure)
# Source of truth: ../.github/workflows/mlflow-ci.yml

name: MLflow CI - Vegetables

on:
  push:
    branches: [main, master]
    paths:
      - "MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject/**"
      - "MSML_Daffa Al-Fathir Ismail/Workflow-CI/.github/workflows/**"
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn matplotlib seaborn pillow kagglehub torch torchvision

      - name: Setup Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download dataset from Kaggle
        run: |
          python - << 'PY'
          import kagglehub
          import os
          import shutil

          print('Downloading Vegetable Image Dataset from Kaggle...')
          path = kagglehub.dataset_download('misrakahmed/vegetable-image-dataset')
          print(f'Downloaded to: {path}')

          target = 'MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject/Vegetables_raw'
          if os.path.exists(target):
              shutil.rmtree(target)
          os.makedirs(os.path.dirname(target), exist_ok=True)

          nested = os.path.join(path, 'Vegetable Images')
          if os.path.exists(nested):
              shutil.move(nested, target)
          else:
              shutil.move(path, target)

          print(f'Dataset ready at: {target}')
          PY

      - name: Run preprocessing (generate CI-ready CSVs)
        run: |
          python "MSML_Daffa Al-Fathir Ismail/Eksperimen_MSML_Daffa_Al-Fathir_Ismail/preprocessing/automate_Daffa.py" \
            --dataset_dir "MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject/Vegetables_raw" \
            --output_dir "MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject/Vegetables_preprocessing"

      - name: Run MLflow Project
        run: |
          cd "MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject"
          python -m mlflow run . \
            --env-manager=local \
            --experiment-name "Vegetables-CI" \
            -P max_train=200 \
            -P max_test=100 \
            -P batch_size=64 \
            -P device=cpu

      - name: Get latest MLflow run id
        run: |
          cd "MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject"
          RUN_ID=$(python - << 'PY'
          import mlflow
          from mlflow.tracking import MlflowClient

          mlflow.set_tracking_uri('file:./mlruns')
          client = MlflowClient()
          exp = client.get_experiment_by_name('Vegetables-CI')
          if exp is None:
              raise SystemExit('Experiment Vegetables-CI not found')
          runs = client.search_runs([exp.experiment_id], order_by=['start_time DESC'], max_results=1)
          if not runs:
              raise SystemExit('No runs found')
          print(runs[0].info.run_id)
          PY
          )
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run: $RUN_ID"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with mlflow build-docker
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd "MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject"
          export MLFLOW_TRACKING_URI="file:./mlruns"
          python -m mlflow models build-docker \
            --model-uri "runs:/${RUN_ID}/model" \
            --name "${DOCKERHUB_USERNAME}/vegetables-mlflow:latest"

      - name: Push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push "${DOCKERHUB_USERNAME}/vegetables-mlflow:latest"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject/mlruns/
            MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject/*.png
            MSML_Daffa Al-Fathir Ismail/Workflow-CI/MLProject/*.txt
          retention-days: 30
